language: node_js
node_js:
  - "0.10"
before_install:
  - npm install wintersmith
script:
  - wintersmith build
after_success: 
  - bash gh-pages-deploy.sh
branches:
  only:
    master
env: 
  global:
    secure: "secure_token_here_quoted"

