language: node_js
node_js:
  - "0.10"
before_install:
  - npm install wintersmith
script:
  - wintersmith build
after_success: 
  - bash ./prepare.sh build/ http://localhost:8080 http://mxklb.github.io/xamblog2013
branches:
  only:
    master
env: 
  global:
    secure: "secure_token_here_quoted"

