language: node_js
node_js:
- '0.10'
before_install:
- npm install wintersmith
script:
- wintersmith build
after_success:
- bash ./prepare.sh build/ http://localhost:8080 http://mxklb.github.io/xamblog2016
- bash ./gh-pages-deploy.sh
branches:
  only: master
env:
  global:
  - secure: b4cV1sV8xfVniuzV7dmXqTivN12ngke3kXEWVocWsNlwibN7Fd2l+fNUQUe2jHsRP+J0+VSYPkKxQDo3AKgZdNZYjsN7sH+cqKZMvbQznzonqquDX51KX2d5OO1KKGpZeqi6qt63EmdgsoMg22SZgkgQHFUj2HbWqMe7vURM73tRwzuwTms+5DqrqIbj6gpBsxwEAGnsBbBc8FYuA0GTZz299HSKe++XEzN8zH5Hf5T+cFgxzHAbWtDGKwC5DtzpDxE2Z7KSk0gA4xVabzsUEGboAW+V9dWX4zVILK4+q0mrw2a9i9zzDk32YEBHK1uH91pQhr7dJlVqRjDFd8JhAwTpOqBahCTMimGioBRoyQN67aiVHm7BUJrhBzt6R4LTqyecYgxyJSIqrnZB0Rc8KY9Hl+6At+k0uvFo1fjwARztTa12tpylE5uFaWeGrZkJtL0TaInf2m1xtlsaHQZiNaldjCLcMEhHLFJ1ALNIl6H8U2/kvLltPahdc0W+CbxOVsTtcNHvzrtUeZ1BiD0zyhx+5NzaQV+w24BEPC/siKnRqiQhAMBDXr8ZN37oL+xCth+QvrB871+qn/rwXBzUaPsml396WlUSYW6aZQo/TvoUIvNB2iPG6Bj5zoDU2Dhgw+mjdQVAShtzoCFRnNKFA7Eb7ffsTogbRsKy2TpNmOU=
