language: node_js
node_js:
- '0.10'
before_install:
- npm install wintersmith
script:
- wintersmith build
after_success:
- bash ./prepare.sh build/ http://localhost:8080 http://mxklb.github.io/xamblog2016
- bash ./gh-pages-deploy.sh
branches:
  only: master
env:
  global:
  - secure: LR97FKDscgRKg8uzzYWwr0ra9C22m8ex5jNICEkJNRsk94OHw37TanOEautxHnmue9hPOyqHLNBJ8LXB1BMFuWG+ZZereOG/n6nZxHKcsOgGQRohncnDc4BLoqDlLS8pOHn/26FUB62tGH9IIo10kwRMqoh4f7Fu6z9Zap8frA4GHMNzVWrgF8pr1ASfg5YTCCh2Mr4we3FLg9wq8FaTohcUFH2RYjciYKBksVfbBdhG6+5AEJeM99JsuUr7PC7Sk+e38q40ty0vocUS1uOBJaU/bGCHQMr72AAf583Ki8P3lbk7Ka6HKAW4104hihYS6h3VqcYCQxtulo+W9kDX6MPGypJNov/xHd+ve0H5W68swrk/fgNenSMVv/nbJczG9Wf+TVlCFJeUs9Fp5EKyiT3jv4dfTGSIT6lcXGLNH+yYspLX399le5tOtqOJ24U5S1VXdtist32dLbbrwbmBAKjOVePTYq2N3ZmicAbY4oVLG+AhbMJIb6fZDZskHCuYNPHD/LWvWW2xmZ/QkXs+0s1Lnu2pDH9EB1vut/v3ofmoRoOatFS+Mc9Kp/lcB/HrHDg8QPjxeoQUlSNWAmNrrhGNEdV/kycnaObS1Un/qpgOhBxtZy0AaEllerSvYxpZdZ0mkFweWog+ug1rGaStXpZLRcfPtHksTwA0YkQeg1I=
