language: node_js
node_js:
- '0.10'
before_install:
- npm install wintersmith
script:
- wintersmith build
after_success:
- bash ./prepare.sh build/ http://localhost:8080 http://mxklb.github.io/xamblog2016
- bash ./gh-pages-deploy.sh
branches:
  only: master
env:
  global:
  - secure: faY42BESF0F/u9l28M+dj6p8DFrQVE57VrzUFyM+elx4bYjE0R47jsTpZF3gmA0V1VOc4KjS1JmczYTX8xyu3AEJQE2UGTZT9PYCLWFqQRvMA+gjaps4sTn3TYJYp3+MVsuz3eonmBDNGtCa09j/g7DpBddB9F02XIehrPQULmi7jagncd24Bjmjx0hL25yJppow9HsRdKOb1uqA8Ur6VkhFNIfwAKplysxkeZqK+Z5pzeuJiquNYUPwDo4JFu0NRW+p2NJyamLnVf/cihlCze+oT7kvjLBHOIEM/V/ZQfXbuzdwuPI9Od6p40kr5fz0V0Fiyyi6RduqTcKTpnYCYlTeL9N+uh5j0RSB+cw2bd0wMdTjTGF5r7MuHEnUHZjoIBR59khkSWvA6lAtb47Sxuc4ejEqq2L004eFydIXzwEdPh7bnX+rCLezWvOcjiWmhRaKew+njuhBVj62WNXfAu9be/5uG7RSWRAuawHcCARt+d5PjIR+rSrP5BUTY41JR1FGERs/nt5q+vlCzB7AlWO6/V/uUnNlYd4CjQWEWgc7qbJQXGbklwQJAkL3rmz1IZzvhx3d25gh01ohR0/xVwGXRvqbg3tlcF4vDlouGeIaTqVkdZ+85+b28fpbN9M4cglr4Y93A7wGfgOMoO1fGiCguWdnZ+RLaoMbGI4Z1Dw=
